/**
 * Card profile data for popular US credit cards.
 * Split from known-card-profiles.ts to stay within file size limits.
 * Contains: Citi, Capital One, Discover, BOA, Amazon Business, Blue Business Plus
 */

import type { KnownCardProfile } from "./known-card-profiles"

export const KNOWN_PROFILES_EXTENDED: readonly KnownCardProfile[] = [
  // ── Citi Strata Elite ──
  {
    keywords: ["strata", "elite"],
    data: {
      cardNetwork: "mastercard",
      rewardType: "points",
      rewardProgram: "Citi ThankYou Points",
      annualFee: 595,
      baseRewardRate: 1.5,
      foreignTransactionFee: "None",
      rewardMultipliers: [
        { category: "Hotels, Car Rentals & Attractions (CitiTravel)", rate: 12, unit: "Points", description: "Booked through CitiTravel.com" },
        { category: "Air Travel (CitiTravel)", rate: 6, unit: "Points", description: "Flights booked through CitiTravel.com" },
        { category: "Restaurants (Citi Nights)", rate: 6, unit: "Points", description: "Fri-Sat 6PM-6AM ET at restaurants" },
        { category: "Restaurants", rate: 3, unit: "Points", description: "All other restaurant purchases including delivery" },
        { category: "All Other Purchases", rate: 1.5, unit: "Points", description: "On all other eligible purchases" },
      ],
      transferPartners: [
        { name: "American Airlines AAdvantage", ratio: "1:1", shortCode: "AA" },
        { name: "Aeromexico Club Premier", ratio: "1:1", shortCode: "AM" },
        { name: "Avianca LifeMiles", ratio: "1:1", shortCode: "AV" },
        { name: "Cathay Pacific Asia Miles", ratio: "1:1", shortCode: "CX" },
        { name: "Emirates Skywards", ratio: "5:4", shortCode: "EK" },
        { name: "Etihad Guest", ratio: "1:1", shortCode: "EY" },
        { name: "EVA Air Infinity MileageLands", ratio: "1:1", shortCode: "BR" },
        { name: "Air France/KLM Flying Blue", ratio: "1:1", shortCode: "AF" },
        { name: "JetBlue TrueBlue", ratio: "1:1", shortCode: "B6" },
        { name: "Qantas Frequent Flyer", ratio: "1:1", shortCode: "QF" },
        { name: "Qatar Airways Privilege Club", ratio: "1:1", shortCode: "QR" },
        { name: "Singapore Airlines KrisFlyer", ratio: "1:1", shortCode: "SQ" },
        { name: "Thai Airways Royal Orchid Plus", ratio: "1:1", shortCode: "TG" },
        { name: "Turkish Airlines Miles&Smiles", ratio: "1:1", shortCode: "TK" },
        { name: "Virgin Atlantic Flying Club", ratio: "1:1", shortCode: "VS" },
        { name: "Wyndham Rewards", ratio: "1:1", shortCode: "WH" },
        { name: "Accor Live Limitless", ratio: "2:1", shortCode: "AL" },
        { name: "Choice Privileges", ratio: "1:2", shortCode: "CH" },
      ],
      benefits: [
        { name: "Hotel Credit (CitiTravel)", description: "Up to $300/year for hotel stays of 2+ nights booked through CitiTravel.com.", icon: "hotel", value: 300 },
        { name: "Splurge Credit", description: "Up to $200/year — choose 2 of: 1stDibs, American Airlines, Best Buy, Future Personal Training, or Live Nation.", icon: "redeem", value: 200 },
        { name: "Blacklane Credit", description: "Up to $200/year ($100 Jan-Jun + $100 Jul-Dec) for Blacklane chauffeur rides.", icon: "local_taxi", value: 200 },
        { name: "Global Entry / TSA PreCheck Credit", description: "Up to $120 every 4 years for Global Entry or TSA PreCheck application fee.", icon: "verified_user", value: 120 },
        { name: "Priority Pass Select", description: "Complimentary Priority Pass Select membership with access to 1,500+ airport lounges. Includes authorized users and up to 2 guests.", icon: "flight", value: 469 },
        { name: "Admirals Club Passes", description: "4 complimentary American Airlines Admirals Club lounge passes per year.", icon: "flight", value: 300 },
        { name: "Trip Cancellation/Interruption Insurance", description: "Enhanced coverage for pre-paid, non-refundable travel expenses.", icon: "flight", value: 10000 },
        { name: "Trip Delay Protection", description: "Coverage for expenses when trips are delayed.", icon: "flight", value: 500 },
        { name: "Lost/Damaged Luggage Protection", description: "Coverage for lost or damaged baggage.", icon: "luggage", value: 3000 },
        { name: "Primary Car Rental Insurance (MasterRental)", description: "Primary coverage for rental vehicle damage or theft.", icon: "car_rental" },
        { name: "Purchase Assurance Plus", description: "Covers eligible purchases against damage or theft.", icon: "shield", value: 10000 },
        { name: "Extended Warranty", description: "Extends manufacturer's warranty on eligible purchases.", icon: "verified_user" },
      ],
      paymentFeatures: [],
    },
  },
  // ── Citi Strata Premier ── (formerly Citi Premier)
  {
    keywords: ["strata", "premier"],
    data: {
      cardNetwork: "mastercard",
      rewardType: "points",
      rewardProgram: "Citi ThankYou Points",
      annualFee: 95,
      baseRewardRate: 1,
      foreignTransactionFee: "None",
      rewardMultipliers: [
        { category: "Hotels, Car Rentals & Attractions (CitiTravel)", rate: 10, unit: "Points", description: "Booked through CitiTravel.com" },
        { category: "Air Travel", rate: 3, unit: "Points", description: "Flights and other air travel purchases" },
        { category: "Hotels", rate: 3, unit: "Points", description: "Hotel purchases not through CitiTravel" },
        { category: "Restaurants", rate: 3, unit: "Points", description: "Restaurants and eligible delivery" },
        { category: "Supermarkets", rate: 3, unit: "Points", description: "U.S. supermarket purchases" },
        { category: "Gas & EV Charging", rate: 3, unit: "Points", description: "Gas stations and EV charging stations" },
        { category: "All Other Purchases", rate: 1, unit: "Points", description: "On all other eligible purchases" },
      ],
      transferPartners: [
        { name: "American Airlines AAdvantage", ratio: "1:1", shortCode: "AA" },
        { name: "Aeromexico Club Premier", ratio: "1:1", shortCode: "AM" },
        { name: "Avianca LifeMiles", ratio: "1:1", shortCode: "AV" },
        { name: "Cathay Pacific Asia Miles", ratio: "1:1", shortCode: "CX" },
        { name: "Emirates Skywards", ratio: "5:4", shortCode: "EK" },
        { name: "Etihad Guest", ratio: "1:1", shortCode: "EY" },
        { name: "EVA Air Infinity MileageLands", ratio: "1:1", shortCode: "BR" },
        { name: "Air France/KLM Flying Blue", ratio: "1:1", shortCode: "AF" },
        { name: "JetBlue TrueBlue", ratio: "1:1", shortCode: "B6" },
        { name: "Qantas Frequent Flyer", ratio: "1:1", shortCode: "QF" },
        { name: "Qatar Airways Privilege Club", ratio: "1:1", shortCode: "QR" },
        { name: "Singapore Airlines KrisFlyer", ratio: "1:1", shortCode: "SQ" },
        { name: "Thai Airways Royal Orchid Plus", ratio: "1:1", shortCode: "TG" },
        { name: "Turkish Airlines Miles&Smiles", ratio: "1:1", shortCode: "TK" },
        { name: "Virgin Atlantic Flying Club", ratio: "1:1", shortCode: "VS" },
        { name: "Wyndham Rewards", ratio: "1:1", shortCode: "WH" },
        { name: "Accor Live Limitless", ratio: "2:1", shortCode: "AL" },
        { name: "Choice Privileges", ratio: "1:2", shortCode: "CH" },
      ],
      benefits: [
        { name: "Hotel Credit (CitiTravel)", description: "$100/year for hotel stays of $500+ (excl. taxes/fees) booked through CitiTravel.com.", icon: "hotel", value: 100 },
        { name: "Trip Delay Protection", description: "Coverage for expenses when trips are delayed.", icon: "flight", value: 500 },
        { name: "Trip Cancellation/Interruption Insurance", description: "Coverage for pre-paid, non-refundable travel expenses.", icon: "flight", value: 5000 },
        { name: "Lost/Damaged Luggage Protection", description: "Coverage for lost or damaged baggage.", icon: "luggage", value: 3000 },
        { name: "Car Rental Insurance (MasterRental)", description: "Coverage for rental vehicle damage or theft.", icon: "car_rental" },
      ],
      paymentFeatures: [],
    },
  },
  // ── Citi Double Cash ──
  {
    keywords: ["double cash"],
    data: {
      cardNetwork: "mastercard",
      rewardType: "cashback",
      rewardProgram: "Citi ThankYou Points",
      annualFee: 0,
      baseRewardRate: 2,
      foreignTransactionFee: "3%",
      rewardMultipliers: [
        { category: "All Purchases", rate: 2, unit: "Cash Back", description: "1% when you buy + 1% when you pay. Effectively 2% on everything when you pay your bill." },
      ],
      transferPartners: [
        { name: "American Airlines AAdvantage", ratio: "1:1", shortCode: "AA" },
        { name: "Aeromexico Club Premier", ratio: "1:1", shortCode: "AM" },
        { name: "Avianca LifeMiles", ratio: "1:1", shortCode: "AV" },
        { name: "Cathay Pacific Asia Miles", ratio: "1:1", shortCode: "CX" },
        { name: "Emirates Skywards", ratio: "5:4", shortCode: "EK" },
        { name: "Etihad Guest", ratio: "1:1", shortCode: "EY" },
        { name: "Air France/KLM Flying Blue", ratio: "1:1", shortCode: "AF" },
        { name: "JetBlue TrueBlue", ratio: "1:1", shortCode: "B6" },
        { name: "Qatar Airways Privilege Club", ratio: "1:1", shortCode: "QR" },
        { name: "Singapore Airlines KrisFlyer", ratio: "1:1", shortCode: "SQ" },
        { name: "Turkish Airlines Miles&Smiles", ratio: "1:1", shortCode: "TK" },
        { name: "Virgin Atlantic Flying Club", ratio: "1:1", shortCode: "VS" },
        { name: "Wyndham Rewards", ratio: "1:1", shortCode: "WH" },
      ],
      benefits: [
        { name: "24/7 Customer Service", description: "Round-the-clock customer support via phone or chat.", icon: "support_agent" },
      ],
      paymentFeatures: [],
    },
  },
  // ── Capital One Venture X ──
  {
    keywords: ["venture", "x"],
    data: {
      cardNetwork: "visa",
      rewardType: "miles",
      rewardProgram: "Capital One Miles",
      annualFee: 395,
      baseRewardRate: 2,
      foreignTransactionFee: "None",
      rewardMultipliers: [
        { category: "Hotels (via Capital One Travel)", rate: 10, unit: "Miles", description: "Hotels booked through Capital One Travel" },
        { category: "Rental Cars (via Capital One Travel)", rate: 10, unit: "Miles", description: "Rental cars booked through Capital One Travel" },
        { category: "Flights (via Capital One Travel)", rate: 5, unit: "Miles", description: "Flights booked through Capital One Travel" },
        { category: "All Other Purchases", rate: 2, unit: "Miles", description: "" },
      ],
      transferPartners: [
        { name: "Turkish Airlines Miles&Smiles", ratio: "1:1", shortCode: "TK" },
        { name: "Air France/KLM Flying Blue", ratio: "1:1", shortCode: "AF" },
        { name: "British Airways Avios", ratio: "1:1", shortCode: "BA" },
        { name: "Singapore Airlines KrisFlyer", ratio: "1:1", shortCode: "SQ" },
        { name: "Qantas Frequent Flyer", ratio: "1:1", shortCode: "QF" },
        { name: "Wyndham Rewards", ratio: "1:1", shortCode: "WH" },
        { name: "Accor Live Limitless", ratio: "1:1", shortCode: "AL" },
      ],
      benefits: [
        { name: "Annual Travel Credit", description: "$300 annual credit for bookings through Capital One Travel. Applied automatically.", icon: "flight", value: 300 },
        { name: "10,000 Anniversary Miles", description: "10,000 bonus miles every account anniversary (worth $100 toward travel).", icon: "stars", value: 100 },
        { name: "Capital One Lounge Access", description: "Complimentary access to Capital One Lounges and Plaza Premium Lounges. 2 free guests per visit.", icon: "flight" },
        { name: "Priority Pass Select", description: "Complimentary Priority Pass membership with unlimited visits. Guests $35 each as of Feb 2026.", icon: "flight", value: 429 },
        { name: "Global Entry / TSA PreCheck Credit", description: "Up to $100 credit every 4 years.", icon: "verified_user", value: 100 },
        { name: "Trip Cancellation/Interruption Insurance", description: "Up to $2,000 per person, $10,000 per trip.", icon: "flight", value: 2000 },
        { name: "Primary Car Rental Insurance", description: "Primary coverage for rental vehicle damage or theft.", icon: "car_rental" },
        { name: "Lost Luggage Reimbursement", description: "Up to $2,500 per passenger.", icon: "luggage", value: 2500 },
        { name: "Purchase Security", description: "Covers theft or damage within 90 days of purchase. Up to $10,000 per claim.", icon: "shield", value: 10000 },
        { name: "Extended Warranty", description: "Extends manufacturer's warranty by 1 additional year.", icon: "verified_user" },
      ],
      paymentFeatures: [],
    },
  },
  // ── Discover It ──
  {
    keywords: ["discover", "it"],
    data: {
      cardNetwork: "discover",
      rewardType: "cashback",
      rewardProgram: null,
      annualFee: 0,
      baseRewardRate: 1,
      foreignTransactionFee: "None",
      rewardMultipliers: [
        { category: "Rotating Quarterly Categories", rate: 5, unit: "Cash Back", description: "Up to $1,500 in combined purchases per quarter. Activation required." },
        { category: "All Other Purchases", rate: 1, unit: "Cash Back", description: "" },
      ],
      transferPartners: [],
      benefits: [
        { name: "Cashback Match", description: "Discover matches all cash back earned in the first year. Automatically applied.", icon: "payments" },
        { name: "Free FICO Score", description: "Free access to your FICO credit score on monthly statements and online.", icon: "monitoring" },
        { name: "No Late Fee on First Late Payment", description: "First late payment fee waived.", icon: "schedule" },
      ],
      paymentFeatures: [],
    },
  },
  // ── Amazon Business Prime Card (Amex) ──
  {
    keywords: ["amazon", "business"],
    data: {
      cardNetwork: "amex",
      rewardType: "cashback",
      rewardProgram: null,
      annualFee: 0,
      baseRewardRate: 1,
      foreignTransactionFee: "2.7%",
      rewardMultipliers: [
        { category: "Amazon, Amazon Business, AWS, Whole Foods", rate: 5, unit: "Cash Back", description: "On first $120,000/year in U.S. purchases, then 1%. Requires Prime or Business Prime membership." },
        { category: "Restaurants", rate: 2, unit: "Cash Back", description: "U.S. restaurants" },
        { category: "Gas Stations", rate: 2, unit: "Cash Back", description: "U.S. gas stations" },
        { category: "Wireless Phone Services", rate: 2, unit: "Cash Back", description: "U.S. wireless telephone services" },
        { category: "All Other Purchases", rate: 1, unit: "Cash Back", description: "" },
      ],
      transferPartners: [],
      benefits: [
        { name: "Purchase Protection", description: "Covers eligible purchases against accidental damage or theft within 90 days. Up to $1,000 per occurrence.", icon: "shield", value: 1000 },
        { name: "Extended Warranty", description: "Extends manufacturer's warranty by up to 1 additional year on warranties of 5 years or less.", icon: "verified_user", value: 10000 },
        { name: "Car Rental Loss & Damage Insurance", description: "Secondary coverage for rental vehicle theft or damage when you decline CDW/LDW.", icon: "car_rental" },
        { name: "Vendor Pay by Bill.com", description: "Pay vendor invoices directly through the card with Bill.com integration.", icon: "payments" },
      ],
      paymentFeatures: [
        { label: "90-Day Payment Terms", description: "Choose 90-day payment terms on select U.S. purchases instead of 5% back (eligible Prime members)" },
      ],
    },
  },
  // ── Blue Business Plus (Amex) ──
  {
    keywords: ["blue", "business", "plus"],
    data: {
      cardNetwork: "amex",
      rewardType: "points",
      rewardProgram: "Amex Membership Rewards",
      annualFee: 0,
      baseRewardRate: 1,
      foreignTransactionFee: "2.7%",
      rewardMultipliers: [
        { category: "All Eligible Purchases", rate: 2, unit: "Points", description: "On first $50,000 in purchases per calendar year, then 1x." },
        { category: "After $50K Cap", rate: 1, unit: "Points", description: "After reaching $50,000 in annual spend" },
      ],
      transferPartners: [
        { name: "Delta SkyMiles", ratio: "1:1", shortCode: "DL" },
        { name: "Hilton Honors", ratio: "1:2", shortCode: "HH" },
        { name: "British Airways Avios", ratio: "1:1", shortCode: "BA" },
        { name: "ANA Mileage Club", ratio: "1:1", shortCode: "NH" },
        { name: "Singapore Airlines KrisFlyer", ratio: "1:1", shortCode: "SQ" },
        { name: "Air France/KLM Flying Blue", ratio: "1:1", shortCode: "AF" },
        { name: "Virgin Atlantic Flying Club", ratio: "1:1", shortCode: "VS" },
        { name: "Marriott Bonvoy", ratio: "1:1", shortCode: "MB" },
        { name: "Aeroplan", ratio: "1:1", shortCode: "AC" },
      ],
      benefits: [
        { name: "Purchase Protection", description: "Covers eligible purchases against accidental damage or theft within 90 days. Up to $1,000 per occurrence, $25,000 per year.", icon: "shield", value: 1000 },
        { name: "Extended Warranty", description: "Extends manufacturer's warranty by up to 1 additional year on warranties of 5 years or less. Up to $10,000 per occurrence.", icon: "verified_user", value: 10000 },
        { name: "Car Rental Loss & Damage Insurance", description: "Secondary coverage for rental vehicle theft or damage when you decline CDW/LDW.", icon: "car_rental" },
        { name: "Dispute Resolution", description: "Amex dispute support for billing errors and merchant issues.", icon: "gavel" },
      ],
      paymentFeatures: [
        { label: "Expanded Buying Power", description: "Spend beyond your credit limit with Expanded Buying Power — amount adjusts with card use, payment history, and financial resources" },
      ],
    },
  },
  // ── BOA Customized Cash Rewards ──
  {
    keywords: ["customized", "cash", "rewards"],
    data: {
      cardNetwork: "visa",
      rewardType: "cashback",
      rewardProgram: null,
      annualFee: 0,
      baseRewardRate: 1,
      foreignTransactionFee: "3%",
      rewardMultipliers: [
        { category: "Choice Category", rate: 3, unit: "Cash Back", description: "3% in your choice of: gas, online shopping, dining, travel, drug stores, or home improvement/furnishings. Up to $2,500/quarter." },
        { category: "Grocery Stores & Wholesale Clubs", rate: 2, unit: "Cash Back", description: "Up to $2,500 in combined grocery/wholesale per quarter." },
        { category: "All Other Purchases", rate: 1, unit: "Cash Back", description: "" },
      ],
      transferPartners: [],
      benefits: [
        { name: "Preferred Rewards Boost", description: "With Bank of America Preferred Rewards, earn 25-75% more cash back on every purchase based on your tier (Gold/Platinum/Platinum Honors).", icon: "trending_up" },
        { name: "Purchase Protection", description: "Covers eligible purchases against damage or theft within 90 days. Up to $500 per claim.", icon: "shield", value: 500 },
        { name: "Extended Warranty", description: "Extends manufacturer's warranty by 1 additional year on warranties of 3 years or less. Up to $10,000 per claim.", icon: "verified_user", value: 10000 },
      ],
      paymentFeatures: [],
    },
  },
]
