/**
 * Plaid personal_finance_category.detailed to internal category mapping.
 */

import type { CategoryResult } from "./category-types"

export const PLAID_CATEGORY_MAP: Record<string, CategoryResult> = {
  "INCOME_DIVIDENDS": { category: "Income", subcategory: "Dividends" },
  "INCOME_INTEREST_EARNED": { category: "Income", subcategory: "Interest" },
  "INCOME_WAGES": { category: "Income", subcategory: "Salary" },
  "INCOME_OTHER_INCOME": { category: "Income", subcategory: null },
  "TRANSFER_IN_DEPOSIT": { category: "Transfer", subcategory: "Bank Transfer" },
  "TRANSFER_OUT_WITHDRAWAL": { category: "Transfer", subcategory: "Bank Transfer" },
  "TRANSFER_IN_ACCOUNT_TRANSFER": { category: "Transfer", subcategory: "Bank Transfer" },
  "TRANSFER_OUT_ACCOUNT_TRANSFER": { category: "Transfer", subcategory: "Bank Transfer" },
  "FOOD_AND_DRINK_GROCERIES": { category: "Food & Dining", subcategory: "Groceries" },
  "FOOD_AND_DRINK_RESTAURANT": { category: "Food & Dining", subcategory: "Restaurants" },
  "FOOD_AND_DRINK_COFFEE": { category: "Food & Dining", subcategory: "Coffee" },
  "FOOD_AND_DRINK_FAST_FOOD": { category: "Food & Dining", subcategory: "Fast Food" },
  "FOOD_AND_DRINK_BEER_WINE_AND_LIQUOR": { category: "Food & Dining", subcategory: "Bars" },
  "TRANSPORTATION_GAS": { category: "Transportation", subcategory: "Gas" },
  "TRANSPORTATION_PARKING": { category: "Transportation", subcategory: "Parking" },
  "TRANSPORTATION_PUBLIC_TRANSIT": { category: "Transportation", subcategory: "Public Transit" },
  "TRANSPORTATION_TAXIS_AND_RIDE_SHARES": { category: "Transportation", subcategory: "Rideshare" },
  "RENT_AND_UTILITIES_RENT": { category: "Housing", subcategory: "Rent" },
  "RENT_AND_UTILITIES_ELECTRICITY": { category: "Bills & Utilities", subcategory: "Electric" },
  "RENT_AND_UTILITIES_GAS": { category: "Bills & Utilities", subcategory: "Gas" },
  "RENT_AND_UTILITIES_WATER": { category: "Bills & Utilities", subcategory: "Water" },
  "RENT_AND_UTILITIES_INTERNET_AND_CABLE": { category: "Bills & Utilities", subcategory: "Internet" },
  "RENT_AND_UTILITIES_TELEPHONE": { category: "Bills & Utilities", subcategory: "Phone" },
  "GENERAL_MERCHANDISE_CLOTHING_AND_ACCESSORIES": { category: "Shopping", subcategory: "Clothing" },
  "GENERAL_MERCHANDISE_ELECTRONICS": { category: "Shopping", subcategory: "Electronics" },
  "GENERAL_MERCHANDISE_ONLINE_MARKETPLACES": { category: "Shopping", subcategory: "Online Shopping" },
  "ENTERTAINMENT_MUSIC_AND_AUDIO": { category: "Entertainment", subcategory: "Music" },
  "ENTERTAINMENT_SPORTING_EVENTS_AMUSEMENT_PARKS_AND_MUSEUMS": { category: "Entertainment", subcategory: "Events" },
  "ENTERTAINMENT_TV_AND_MOVIES": { category: "Entertainment", subcategory: "Streaming" },
  "ENTERTAINMENT_VIDEO_GAMES": { category: "Entertainment", subcategory: "Gaming" },
  "MEDICAL_DENTAL_CARE": { category: "Health & Fitness", subcategory: "Dentist" },
  "MEDICAL_EYE_CARE": { category: "Health & Fitness", subcategory: "Vision" },
  "MEDICAL_PHARMACIES_AND_SUPPLEMENTS": { category: "Health & Fitness", subcategory: "Pharmacy" },
  "MEDICAL_PRIMARY_CARE": { category: "Health & Fitness", subcategory: "Doctor" },
  "PERSONAL_CARE_HAIR_AND_BEAUTY": { category: "Personal Care", subcategory: "Hair" },
  "TRAVEL_FLIGHTS": { category: "Travel", subcategory: "Flights" },
  "TRAVEL_LODGING": { category: "Travel", subcategory: "Hotels" },
  "TRAVEL_RENTAL_CARS": { category: "Travel", subcategory: "Rental Car" },
  "LOAN_PAYMENTS_MORTGAGE_PAYMENT": { category: "Housing", subcategory: "Mortgage" },
  "LOAN_PAYMENTS_CAR_PAYMENT": { category: "Transportation", subcategory: "Car Payment" },
  "LOAN_PAYMENTS_STUDENT_LOAN_PAYMENT": { category: "Education", subcategory: "Student Loan" },
  "BANK_FEES_ATM_FEES": { category: "Fees & Charges", subcategory: "ATM Fee" },
  "BANK_FEES_OVERDRAFT_FEES": { category: "Fees & Charges", subcategory: "Bank Fee" },
  "BANK_FEES_FOREIGN_TRANSACTION_FEES": { category: "Fees & Charges", subcategory: "Bank Fee" },
  "LOAN_PAYMENTS_CREDIT_CARD_PAYMENT": { category: "Transfer", subcategory: "Bank Transfer" },
  "LOAN_PAYMENTS_OTHER_PAYMENT": { category: "Transfer", subcategory: "Bank Transfer" },
  "TRANSFER_IN_CASH_ADVANCES_AND_LOANS": { category: "Transfer", subcategory: "Bank Transfer" },
  "TRANSFER_CREDIT": { category: "Transfer", subcategory: "Bank Transfer" },
  "TRANSFER_DEBIT": { category: "Transfer", subcategory: "Bank Transfer" },
  "GENERAL_MERCHANDISE_DEPARTMENT_STORES": { category: "Shopping", subcategory: "Department Store" },
  "GENERAL_MERCHANDISE_SPORTING_GOODS": { category: "Shopping", subcategory: null },
  "GENERAL_MERCHANDISE_HOME_IMPROVEMENT": { category: "Housing", subcategory: "Home Improvement" },
  "GENERAL_MERCHANDISE_PET_SUPPLIES": { category: "Shopping", subcategory: null },
  "GENERAL_MERCHANDISE_BOOKSTORES_AND_NEWSSTANDS": { category: "Shopping", subcategory: null },
  "GENERAL_SERVICES_POSTAGE_AND_SHIPPING": { category: "Shopping", subcategory: "Shipping" },
  "GENERAL_SERVICES_CONSULTING_AND_LEGAL": { category: "Fees & Charges", subcategory: "Professional Services" },
  "GENERAL_SERVICES_INSURANCE": { category: "Bills & Utilities", subcategory: "Insurance" },
  "GENERAL_SERVICES_ACCOUNTING_AND_FINANCIAL_PLANNING": { category: "Fees & Charges", subcategory: "Financial Services" },
  "GENERAL_SERVICES_AUTOMOTIVE": { category: "Transportation", subcategory: "Auto Services" },
  "GENERAL_SERVICES_CHILDCARE": { category: "Personal Care", subcategory: "Childcare" },
  "GENERAL_SERVICES_HOME_IMPROVEMENT": { category: "Housing", subcategory: "Home Improvement" },
  "GENERAL_SERVICES_STORAGE": { category: "Bills & Utilities", subcategory: "Storage" },
  "GENERAL_SERVICES_VETERINARY_SERVICES": { category: "Shopping", subcategory: "Pets" },
  "MEDICAL_VETERINARY_SERVICES": { category: "Shopping", subcategory: "Pets" },
  "MEDICAL_MENTAL_HEALTH_CARE": { category: "Health & Fitness", subcategory: "Mental Health" },
  "MEDICAL_OTHER_MEDICAL": { category: "Health & Fitness", subcategory: null },
  "PERSONAL_CARE_LAUNDRY_AND_DRY_CLEANING": { category: "Personal Care", subcategory: null },
  "FOOD_AND_DRINK_OTHER_FOOD_AND_DRINK": { category: "Food & Dining", subcategory: null },
  "FOOD_AND_DRINK_BAKERY": { category: "Food & Dining", subcategory: null },
  "ENTERTAINMENT_CASINOS_AND_GAMBLING": { category: "Entertainment", subcategory: null },
  "GOVERNMENT_AND_NON_PROFIT_DONATIONS": { category: "Gifts & Donations", subcategory: "Donations" },
  "GOVERNMENT_AND_NON_PROFIT_TAX_PAYMENT": { category: "Fees & Charges", subcategory: "Taxes" },
  "GENERAL_MERCHANDISE_GIFTS_AND_NOVELTIES": { category: "Gifts & Donations", subcategory: "Gifts" },
  "GENERAL_MERCHANDISE_DISCOUNT_STORES": { category: "Shopping", subcategory: null },
  "GENERAL_MERCHANDISE_SUPERSTORES": { category: "Shopping", subcategory: null },
  "GENERAL_MERCHANDISE_TOBACCO_AND_VAPE": { category: "Shopping", subcategory: null },
  // Primary-level fallbacks (when only PRIMARY category is provided)
  "GENERAL_SERVICES": { category: "Shopping", subcategory: "Services" },
  "GENERAL_MERCHANDISE": { category: "Shopping", subcategory: null },
  "MEDICAL": { category: "Health & Fitness", subcategory: null },
  "PERSONAL_CARE": { category: "Personal Care", subcategory: null },
  "ENTERTAINMENT": { category: "Entertainment", subcategory: null },
  "FOOD_AND_DRINK": { category: "Food & Dining", subcategory: null },
  "TRANSPORTATION": { category: "Transportation", subcategory: null },
  "RENT_AND_UTILITIES": { category: "Bills & Utilities", subcategory: null },
  "TRAVEL": { category: "Travel", subcategory: null },
  "INCOME": { category: "Income", subcategory: null },
  "TRANSFER_IN": { category: "Transfer", subcategory: "Bank Transfer" },
  "TRANSFER_OUT": { category: "Transfer", subcategory: "Bank Transfer" },
  "LOAN_PAYMENTS": { category: "Transfer", subcategory: "Bank Transfer" },
  "BANK_FEES": { category: "Fees & Charges", subcategory: "Bank Fee" },
  "GOVERNMENT_AND_NON_PROFIT": { category: "Fees & Charges", subcategory: null },
}
