export const CATEGORY_ICONS: Record<string, string> = {
  dining: "restaurant",
  restaurants: "restaurant",
  travel: "flight",
  groceries: "shopping_cart",
  "online grocery": "shopping_cart",
  gas: "local_gas_station",
  entertainment: "movie",
  streaming: "live_tv",
  "select streaming": "live_tv",
  "online shopping": "shopping_bag",
  online: "shopping_bag",
  drugstores: "local_pharmacy",
  transit: "directions_transit",
  "select transit": "directions_transit",
  hotels: "hotel",
  flights: "flight",
  rideshare: "local_taxi",
}
